;; This code was automatically generated by the 'metav' library.
(ns atomist.skill-meta)

(def module-name "update-npm-dependencies-skill")
(def path ".")
(def version "0.1.19")
(def tag "v0.1.19")
(def generated-at "2020-05-01T01:01:39Z")
