;; This code was automatically generated by the 'metav' library.
(ns atomist.skill-meta)

(def module-name "update-npm-dependencies-skill")
(def path ".")
(def version "0.3.0")
(def tag "v0.3.0")
(def generated-at "2020-05-15T05:19:56Z")
