;; This code was automatically generated by the 'metav' library.
(ns atomist.skill-meta)

(def module-name "update-npm-dependencies-skill")
(def path ".")
(def version "0.2.5")
(def tag "v0.2.5")
(def generated-at "2020-05-02T05:15:56Z")
